### ISSUE TITLE
Maven 3.3 support

### ISSUE THREAD

**Issue by RainerW** [ykryshchuk/umlet-maven-plugin#6]
When running the project attached to ticket #5 with maven 3.3.3 there seems to be a SLF4j API missmatch: (works with maven 3.0.5)

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.kryshchuk.maven.plugins:umlet-maven-plugin:1.1.6:convert (default-cli) on project umlet-test:
xecution default-cli of goal com.kryshchuk.maven.plugins:umlet-maven-plugin:1.1.6:convert failed: A required class was missing wh
le executing com.kryshchuk.maven.plugins:umlet-maven-plugin:1.1.6:convert: org/slf4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.kryshchuk.maven.plugins:umlet-maven-plugin:1.1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Rainer/.m2/repository/com/kryshchuk/maven/plugins/umlet-maven-plugin/1.1.6/umlet-maven-plugin-1.
.6.jar
[ERROR] urls[1] = file:/C:/Users/Rainer/.m2/repository/com/umlet/umlet/12.0/umlet-12.0.jar
[ERROR] urls[2] = file:/C:/Users/Rainer/.m2/repository/org/sourceforge/jlibeps/jlibeps/0.1/jlibeps-0.1.jar
[ERROR] urls[3] = file:/C:/Users/Rainer/.m2/repository/com/itextpdf/itextpdf/5.0.6/itextpdf-5.0.6.jar
[ERROR] urls[4] = file:/C:/Users/Rainer/.m2/repository/org/bouncycastle/bcmail-jdk14/1.38/bcmail-jdk14-1.38.jar
[ERROR] urls[5] = file:/C:/Users/Rainer/.m2/repository/org/bouncycastle/bcprov-jdk14/1.38/bcprov-jdk14-1.38.jar
[ERROR] urls[6] = file:/C:/Users/Rainer/.m2/repository/org/bouncycastle/bctsp-jdk14/1.38/bctsp-jdk14-1.38.jar
[ERROR] urls[7] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-svggen/1.7/batik-svggen-1.7.jar
[ERROR] urls[8] = file:/C:/Users/Rainer/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
[ERROR] urls[9] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-util/1.7/batik-util-1.7.jar
[ERROR] urls[10] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-ext/1.7/batik-ext-1.7.jar
[ERROR] urls[11] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-awt-util/1.7/batik-awt-util-1.7.jar
[ERROR] urls[12] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-dom/1.7/batik-dom-1.7.jar
[ERROR] urls[13] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-css/1.7/batik-css-1.7.jar
[ERROR] urls[14] = file:/C:/Users/Rainer/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.jar
[ERROR] urls[15] = file:/C:/Users/Rainer/.m2/repository/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar
[ERROR] urls[16] = file:/C:/Users/Rainer/.m2/repository/org/apache/xmlgraphics/batik-xml/1.7/batik-xml-1.7.jar
[ERROR] urls[17] = file:/C:/Users/Rainer/.m2/repository/log4j/log4j/1.2.15/log4j-1.2.15.jar
[ERROR] urls[18] = file:/C:/Users/Rainer/.m2/repository/javax/mail/mail/1.4/mail-1.4.jar
[ERROR] urls[19] = file:/C:/Users/Rainer/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[20] = file:/C:/Users/Rainer/.m2/repository/com/kryshchuk/maven/plugins/file-visitor/1.0.8/file-visitor-1.0.8.jar
[ERROR] urls[21] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[22] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[23] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[24] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[25] = file:/C:/Users/Rainer/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.j
r
[ERROR] urls[26] = file:/C:/Users/Rainer/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-a
notations-1.5.5.jar
[ERROR] urls[27] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.j
r
[ERROR] urls[28] = file:/C:/Users/Rainer/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[29] = file:/C:/Users/Rainer/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.10/plexus-utils-3.0.10.jar
[ERROR] urls[30] = file:/C:/Users/Rainer/.m2/repository/com/googlecode/slf4j-maven-plugin-log/slf4j-maven-plugin-log/1.0.0/slf4j-
aven-plugin-log-1.0.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.slf4j.helpers.MarkerIgnoringBase
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by ykryshchuk** [comment]
Hi Rainer, 

thank you for the report. I am busy this week and next week as well. Will check the issue when I am back. 

Thanks

**Comment by RainerW** [comment]
Thanks for the fast reply, but this is currently just a minor issue. The build Servers are using maven 3.1. So this is currently not a 'real' problem.

**Comment by barthel** [comment]
Maven 3.3 will be more and more used. Do you have a solution or do you need any assistance here?

**Comment by ykryshchuk** [comment]
Hi, 

well, I will check the issue again in first weeks of November. 
But if you have any ideas you may do a fork and propose a fix. :)

**Comment by barthel** [comment]
See https://issues.apache.org/jira/browse/MNG-5787

**Comment by ykryshchuk** [comment]
The fix comes with next releae

**Comment by ykryshchuk** [comment]
released version 1.2, which should be available soon on maven central
